apiVersion: v1
kind: Pod
metadata:
  name: jhandl-ddiag
spec:

  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  containers:
  - name: ddiag
    image: hub.cerit.io/josef_handl/ddiag:22.04
    imagePullPolicy: Always

    securityContext:
      privileged: false
      runAsUser: 1000
      runAsGroup: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
